fix error running post update commands
Fixes this error:

Error: /Stage[main]/Nextcloud::Update/Exec[post-update command]: Could not evaluate: Working directory /opt/nextcloud-24.0.7/nextcloud does not exist!

This error would only occur when $update_host is set and the update
was not completed yet.